name = "uveldt"
uuid = "bf1fc462-6d4b-43a2-8842-d2d1a662c470"
keywords = ["evolution", "biochemistry", "microbiology", "phylogenetics", "simulator"]
license = "MIT"
desc = "Evolution and biochemistry of digital microbes"
version = "0.0.1"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
